config/routes.rb
Rails.application.routes.draw do
  get 'favorites/index'
  devise_for :users
  # get 'friends/index'
  # get 'friends/show'
  # get 'friends/edit'
  # get 'friends/new'
  resources :blogs
  get '/students',to: "students#index"
  post '/students',to: 'students#create'
  get '/students/new',to: "students#new"
  get '/students/:id/edit',to: "students#edit", as: "edit_student"
  get '/students/:id' => "students#show", as: :student
  get '/student_destroy/:id',to: "students#destroy", as: :student_destroy
  get 'student_details/:id' => "students#student_details", as: :details
  post 'create' => 'comments#create'
  get '/comments/:id', to: 'comments#remove'
  get '/favorites', to: 'favorites#index'
  # resources :students
  # get '/students/:id',to: "students#show"
  post '/students/:id', to: "students#update"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :posts
  # Defines the root path route ("/")
  root "students#index"
  

  resources :products do 
    resources :reviews
    get 'add_favorite'
    get 'remove_favorite'
  end
  
  resources :friends
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
	validates :title, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :friend

end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :product
	belongs_to :user
end

app/models/friend.rb
class Friend < ApplicationRecord
	has_many :comments

	# validates :name, presence: true
	# validate :check_date

	# def check_date
	# 	return if end_date.blank? || start_date.blank?
	# 	if end_date < start_date
	#     errors.add(:end_date, "cannot be before the start date") 
	#   end 
	# end
end

app/models/product.rb
class Product < ApplicationRecord
	validates :name, :price, presence: true
	mount_uploader :image, AvatarUploader
	has_many :reviews
	has_many :favorites, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
	belongs_to :product
end

app/models/student.rb
class Student < ApplicationRecord
	has_many :comments

	validates :name, presence: true
	validate :check_date

	def check_date
		return if end_date.blank? || start_date.blank?
		if end_date < start_date
	    errors.add(:end_date, "cannot be before the start date") 
	  end 
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :favorites, dependent: :destroy
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[ show edit update destroy ]

  # GET /blogs or /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1 or /blogs/1.json
  def show
    @blogs = Blog.all
  end

  # GET /blogs/new  
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs or /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully created." }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully updated." }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "Blog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :description)
    end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  def index
  	@friend = Friend.paginate(page: params[:page],per_page:3)
  end


  def new
  	@friend = Friend.new
  end


	def create
		@friend = Friend.new(first_name: params[:friend][:first_name], last_name:  params[:friend][:last_name],email:  params[:friend][:email], gender:  params[:friend][:gender], phone_no: params[:friend][:phone_no])
		if @friend.save
  		redirect_to friend_path(@friend)
  	else
  		render :new, status: :unprocessable_entity
  	end
	end	

  def show
  	@friend = Friend.find(params[:id])
  end


  def edit
  	@friend = Friend.find(params[:id])
  end

  def update
    @friend = Friend.find(params[:id])
  	 respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
     @friend = Friend.find(params[:id])
    @friend.destroy
    respond_to do |format|
      format.html{redirect_to friends_url, notice: "friend was successfully destroyed."}
      format.json{head :no_content }
    end
  end

    private
    def  friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :gender, :phone_no)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	def create
		@product = Product.find(params[:product_id])
		@review = @product.reviews.create(review_params)
		redirect_to product_path(@product)

end

private
   def review_params
   	params.require(:review).permit(:content )
   end
end

# article = product
# review = comment 


# class CommentsController < ApplicationController
#   def create
#     @article = Article.find(params[:article_id])
#     @comment = @article.comments.create(comment_params)
#     redirect_to article_path(@article)
#   end

#   private
#     def comment_params
#       params.require(:comment).permit(:commenter, :body)
#     end
# end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/friend_helper.rb
module FriendHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/lenevo_helper.rb
module LenevoHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/blogs/_blog.html.erb
<div id="<%= dom_id blog %>">

</div>

app/views/blogs/_form.html.erb
<%= form_with(model: blog) do |form| %>
  <% if blog.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing blog</h1>

<%= render "form", blog: @blog %>

<br>

<div>
  <%= link_to "Show this blog", @blog %> |
  <%= link_to "Back to blogs", blogs_path %>
</div>

app/views/blogs/index.html.erb
<p style="color: green"><%= notice %></p>
<a href="/blogs/new">new record</a>
<table class="table">
  <h1>blog Record</h1>
  <thead>    
    <tr><br>
      <th></th>
        <th>Name</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each_with_index do |blog, sindex| %>
      <tr>
        <td><%= sindex+1 %></td>
        <td><%= blog.name %></td>
        <td><%= link_to "Show", blog %></td>
        <td><%= link_to "Edit", edit_blog_path(blog) %></td>
        <td><%= button_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/blogs/new.html.erb
<h1>New blog</h1>

app/views/blogs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @blog %>

<div>
  <%= link_to "Edit this blog", edit_blog_path(@blog) %> |
  <%= link_to "Back to blogs", blogs_path %>

  <%= button_to "Destroy this blog", @blog, method: :delete %>
</div>