config/routes.rb
Rails.application.routes.draw do
  get 'favorites/index'
  devise_for :users
  # get 'friends/index'
  # get 'friends/show'
  # get 'friends/edit'
  # get 'friends/new'
  resources :blogs
  get '/students',to: "students#index"
  post '/students',to: 'students#create'
  get '/students/new',to: "students#new"
  get '/students/:id/edit',to: "students#edit", as: "edit_student"
  get '/students/:id' => "students#show", as: :student
  get '/student_destroy/:id',to: "students#destroy", as: :student_destroy
  get 'student_details/:id' => "students#student_details", as: :details
  post 'create' => 'comments#create'
  get '/comments/:id', to: 'comments#remove'
  get '/favorites', to: 'favorites#index'
  # resources :students
  # get '/students/:id',to: "students#show"
  post '/students/:id', to: "students#update"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :posts
  # Defines the root path route ("/")
  root "students#index"
  

  resources :products do 
    resources :reviews
    get 'add_favorite'
    get 'remove_favorite'
  end
  
  resources :friends
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
	validates :title, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :friend

end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :product
	belongs_to :user
end

app/models/friend.rb
class Friend < ApplicationRecord
	has_many :comments

	# validates :name, presence: true
	# validate :check_date

	# def check_date
	# 	return if end_date.blank? || start_date.blank?
	# 	if end_date < start_date
	#     errors.add(:end_date, "cannot be before the start date") 
	#   end 
	# end
end

app/models/product.rb
class Product < ApplicationRecord
	validates :name, :price, presence: true
	mount_uploader :image, AvatarUploader
	has_many :reviews
	has_many :favorites, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
	belongs_to :product
end

app/models/student.rb
class Student < ApplicationRecord
	has_many :comments

	validates :name, presence: true
	validate :check_date

	def check_date
		return if end_date.blank? || start_date.blank?
		if end_date < start_date
	    errors.add(:end_date, "cannot be before the start date") 
	  end 
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :favorites, dependent: :destroy
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[ show edit update destroy ]

  # GET /blogs or /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1 or /blogs/1.json
  def show
    @blogs = Blog.all
  end

  # GET /blogs/new  
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs or /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully created." }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully updated." }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "Blog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :description)
    end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  def index
  	@friend = Friend.paginate(page: params[:page],per_page:3)
  end


  def new
  	@friend = Friend.new
  end


	def create
		@friend = Friend.new(first_name: params[:friend][:first_name], last_name:  params[:friend][:last_name],email:  params[:friend][:email], gender:  params[:friend][:gender], phone_no: params[:friend][:phone_no])
		if @friend.save
  		redirect_to friend_path(@friend)
  	else
  		render :new, status: :unprocessable_entity
  	end
	end	

  def show
  	@friend = Friend.find(params[:id])
  end


  def edit
  	@friend = Friend.find(params[:id])
  end

  def update
    @friend = Friend.find(params[:id])
  	 respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
     @friend = Friend.find(params[:id])
    @friend.destroy
    respond_to do |format|
      format.html{redirect_to friends_url, notice: "friend was successfully destroyed."}
      format.json{head :no_content }
    end
  end

    private
    def  friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :gender, :phone_no)
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
  	@students = Student.paginate(page: params[:page], per_page: 10)
  end

  def new
  	@student = Student.new
  end

  def create 
  	@student =  Student.new(name: params[:student][:name], email: params[:student][:email], rollno: params[:student][:rollno], gender: params[:student][:gender], city: params[:student][:city] ,address: params[:student][:address],start_date:params[:student][:start_date], end_date: params[:student][:end_date])
  	if @student.save
  		redirect_to student_path(@student)
  	else
  		render :new, status: :unprocessable_entity
  	end
  end

  def show
    @student = Student.find_by(id: params[:id])
    if @student.present?
    else
      redirect_to students_path
    end
  end

  def student_details
    @bhanu = Student.find(params[:id]) 
  end

  def edit
   @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])
  	 respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to student_url(@student), notice: "student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
     @student = Student.find(params[:id])
    @student.destroy
    respond_to do |format|
      format.html{redirect_to students_url, notice: "student was successfully destroyed."}
      format.json{head :no_content }
    end
  
  end
  private
    def  student_params
      params.require(:student).permit(:name, :email, :rollno, :gender, :city , :address, :start_date, :end_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/friend_helper.rb
module FriendHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/lenevo_helper.rb
module LenevoHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_with(model: student, :method=>"post") do |form| %>
  <% if student.errors.any? %>
    <div style="color: red">
      <!-- <h2><%#= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2> -->

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %> 
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
	  </div>
  </div>

  <div>
    <%= form.label :email %><br>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :rollnumber %><br>
    <%= form.text_field :rollno %>
  </div>
  <div>
    <%= form.label :gender %><br>
    <%= form.text_field :gender %>
  </div>
  <div>
    <%= form.label :city %><br>
    <%= form.text_field :city %>
  </div>

  <div>
    <%= form.label :address %><br>
    <%= form.text_field :address %>
  </div>
  <div>
    <%= form.label :start_date %><br>
    <%= form.date_field :start_date %>
  </div><br>

  <div>
    <%= form.label :end_date %><br>
    <%= form.date_field :end_date %>
  </div><br>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Show this student", @student %> |
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/index.html.erb
<p style="color: green"><%= notice %></p>
<a href="/students/new" class="btn btn-outline-success">New Record</a>
<table class="table">
  <h1>student Record</h1>
  <thead>
    <h3><%= will_paginate @student %></h3>
    <tr><br>
      <th></th>
        <th>Name</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @students.each_with_index do |student, sindex| %>
      <tr>
        <td><%= sindex+1 %></td>
        <td><%= student.name %></td>
        <td><%= link_to "Show", student,class: "btn btn-primary" %></td>
        <td><%= link_to "Edit", edit_student_path(student), class: "btn btn-warning" %></td>
        <td><%= link_to "Destroy", student_destroy_path(student), method: :delete, class: "btn btn-danger"%></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/students/new.html.erb
<h1>New Student</h1>
<%= render "form",student:@student%>

app/views/students/show.html.erb
<div class="row">
  <h1>Student Record</h1>
  <div class="ragister">
    Name  :      <%= @student.name %><br>
    Email  :     <%= @student.email %><br>
    RollNumber : <%= @student.rollno %><br>
    Gender  :    <%= @student.gender %><br>
    City  :      <%= @student.city %><br>
    address :    <%= @student.address %><br>
    Start_date : <%= @student.start_date %><br>
    end_date :   <%= @student.end_date %><br>

    <div>
      <%= link_to "Edit this student", edit_student_path(@student) %><br>
      <%= link_to "Back to students", students_path %>
      <br>
    
      <%= link_to "Destroy this student", student_destroy_path(@student), method: :delete%>
    </div>


    <h2>Comments</h2>
	<% @student.comments.where.not(title: [nil, ""]).order("id DESC").first(2).each do |comment| %>

	  <p>
	    <strong>Comment:</strong>
	    <%= comment.title %>
	  </p>
	<% end %>


    <%= form_tag '/create', :method => 'post' do %>
			<%= hidden_field_tag "student_id" ,nil, value:  @student.id %>
			<p>
		    <%= text_field_tag :title %>
		    <%= submit_tag "Comment", :name => nil %>
		  </p> 
	<% end %>
  </div>
</div>









<style >
	body{
		background-color: red;
	}
	*{
		margin: 0px;
		padding: 0px;
	}
	.row{
		width: 438px;
		height: auto;
				
		background-color: white;
		margin-left: 30%;

	}
	h1{
		text-align: center;
		color: rgba(204, 43, 43, 0.8)

	}
	.ragister{
		color: blue;
		margin-left: 60px;
		
		font-size:22px;
	}
</style>

app/views/students/student_details.html.erb
<body>
    <div class="row">
        <h1>Student Record</h1>
        <div class="ragister">
              Name  :      <%= @bhanu.name%><br>
              Email  :     <%= @bhanu.email%><br>
              RollNumber : <%= @bhanu.rollno%><br>
              Gender  :    <%= @bhanu.gender%><br>
              City  :      <%= @bhanu.city %><br>
              address :    <%= @bhanu.address %><br>
              start_date : <%= @bhanu.start_date %><br>
              end_date :   <%= @bhanu.end_date %><br>
        
              <div>
                <%= link_to "Edit this student", edit_student_path(@bhanu) %><br>
                <%= link_to "Back to students", students_path %>
                <br>
              
                <%#= link_to "Destroy this student", student_path(@bhanu), method: :delete%>
                <%= link_to 'Destroy', student_destroy_path(@bhanu), method: :delete, data: { confirm: 'Are you sure?' } %>
              </div>
        </div>
    </div>
    
</body>
<style >
	body{
		background-color: red;
	}
	*{
		margin: 0px;
		padding: 0px;
	}
	.row{
				
		background-color: white;
		margin-left: 30%;

	}
	h1{
		text-align: center;
		color: rgba(204, 43, 43, 0.8)

	}
	.ragister{
		color: blue;
		margin-left: 60px;
		
		font-size:22px;
	}
</style>