config/routes.rb
Rails.application.routes.draw do
  get 'favorites/index'
  devise_for :users
  # get 'friends/index'
  # get 'friends/show'
  # get 'friends/edit'
  # get 'friends/new'
  resources :blogs
  get '/students',to: "students#index"
  post '/students',to: 'students#create'
  get '/students/new',to: "students#new"
  get '/students/:id/edit',to: "students#edit", as: "edit_student"
  get '/students/:id' => "students#show", as: :student
  get '/student_destroy/:id',to: "students#destroy", as: :student_destroy
  get 'student_details/:id' => "students#student_details", as: :details
  post 'create' => 'comments#create'
  get '/comments/:id', to: 'comments#remove'
  get '/favorites', to: 'favorites#index'
  # resources :students
  # get '/students/:id',to: "students#show"
  post '/students/:id', to: "students#update"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :posts
  # Defines the root path route ("/")
  root "students#index"
  

  resources :products do 
    resources :reviews
    get 'add_favorite'
    get 'remove_favorite'
  end
  
  resources :friends
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
	validates :title, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :friend

end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :product
	belongs_to :user
end

app/models/friend.rb
class Friend < ApplicationRecord
	has_many :comments

	# validates :name, presence: true
	# validate :check_date

	# def check_date
	# 	return if end_date.blank? || start_date.blank?
	# 	if end_date < start_date
	#     errors.add(:end_date, "cannot be before the start date") 
	#   end 
	# end
end

app/models/product.rb
class Product < ApplicationRecord
	validates :name, :price, presence: true
	mount_uploader :image, AvatarUploader
	has_many :reviews
	has_many :favorites, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
	belongs_to :product
end

app/models/student.rb
class Student < ApplicationRecord
	has_many :comments

	validates :name, presence: true
	validate :check_date

	def check_date
		return if end_date.blank? || start_date.blank?
		if end_date < start_date
	    errors.add(:end_date, "cannot be before the start date") 
	  end 
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :favorites, dependent: :destroy
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[ show edit update destroy ]

  # GET /blogs or /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1 or /blogs/1.json
  def show
    @blogs = Blog.all
  end

  # GET /blogs/new  
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs or /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully created." }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully updated." }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "Blog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :description)
    end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  def index
  	@friend = Friend.paginate(page: params[:page],per_page:3)
  end


  def new
  	@friend = Friend.new
  end


	def create
		@friend = Friend.new(first_name: params[:friend][:first_name], last_name:  params[:friend][:last_name],email:  params[:friend][:email], gender:  params[:friend][:gender], phone_no: params[:friend][:phone_no])
		if @friend.save
  		redirect_to friend_path(@friend)
  	else
  		render :new, status: :unprocessable_entity
  	end
	end	

  def show
  	@friend = Friend.find(params[:id])
  end


  def edit
  	@friend = Friend.find(params[:id])
  end

  def update
    @friend = Friend.find(params[:id])
  	 respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
     @friend = Friend.find(params[:id])
    @friend.destroy
    respond_to do |format|
      format.html{redirect_to friends_url, notice: "friend was successfully destroyed."}
      format.json{head :no_content }
    end
  end

    private
    def  friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :gender, :phone_no)
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	 def index
  	@products = Product.paginate(page: params[:page], per_page: 10)
  end

	def new
		@product = Product.new
	end

	def create
		@product = Product.new(name: params[:product][:name], description:  params[:product][:description], image: params[:product][:image], price: params[:product][:price] )
		if @product.save
  		redirect_to product_path(@product)
  	else
  		render :new, status: :unprocessable_entity
  	end
	end	

  def show
  	@product = Product.find(params[:id])
  end

  def add_favorite
    @product = Product.find_by(id: params[:product_id])
    @favorite = Favorite.create(user_id: current_user.id, product_id: @product.id)
    redirect_to product_url(@product), notice: "Successfully added your favorite list."
  end

  def remove_favorite
    @product = Product.find_by(id: params[:product_id])
    favorite = Favorite.where(user_id: current_user.id, product_id: @product.id).last
    if favorite.present?
      favorite.destroy
      redirect_to product_url(@product), notice: "Successfully removed your favorite list."
    end
  end


  def edit
   @product = Product.find(params[:id])
  end

  def update

    @product = Product.find(params[:id])
  	 respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
     @product = Product.find(params[:id])
    @product.destroy
    respond_to do |format|
      format.html{redirect_to products_url, notice: "product was successfully destroyed."}
      format.json{head :no_content }
    end
  end
  

  private
    def  product_params
      params.require(:product).permit(:name, :description, :image, :price)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/friend_helper.rb
module FriendHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/lenevo_helper.rb
module LenevoHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <!-- <h2><%#= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2> -->

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
	  </div>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :image %><br>
    <%= form.file_field :image %>
  </div>
  <div>
    <%= form.label :price %><br>
    <%= form.number_field :price %>
  </div><br>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<p style="color: green"><%= notice %></p>
<a href="/products/new" class="btn btn-outline-info">new record</a>
<table class="table">
  <h1>product Record</h1>
  <thead>
    <h3><%= will_paginate @product %></h3>
    <tr><br>
      <th></th>
        <th>Name</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @products.each_with_index do |product, sindex| %>
      <tr>
        <td><%= sindex+1 %></td>
        <td><%= product.name %></td>
        <td><%= link_to "Show", product, class: "btn btn-info" %></td>
        <td><%= link_to "Edit", edit_product_path(product), class: "btn btn-primary" %></td>
        <td><%= button_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>  

app/views/products/new.html.erb
<h1>New product</h1>
<%= render "form",product:@product%>

app/views/products/show.html.erb
<div class="row">
  <h1>product Record</h1>
  <div class="ragister">
    Name  :           <%= @product.name%><br>
    Description  :     <%= @product.description %><br>
    image :           <% if @product.image.present? %><%= image_tag @product.image&.url, style: "width:100px;" "height:30px;" %><% end %><br>
    price  :          <%= @product.price %><br>
    <div>
      <%= link_to "Edit this product", edit_product_path(@product) %><br>
      <%= link_to "Back to products", products_path %>
      <br>
    
      <%= button_to "Destroy this product", @product, method: :delete%>
      <% if Favorite.where(user_id: current_user.id, product_id: @product.id).any? %>
      	<%= link_to "Remove Favorite", product_remove_favorite_path(@product) %>
      <% else %>
      	<%= link_to "Add Favorite", product_add_favorite_path(@product) %>
      <% end %>
    </div>

<h2>Comments</h2>
<% @product.reviews.each do |review| %>
  <p>
    <strong>Commenter:</strong>
    <%= review.content %>
  </p>
<% end %>

    <h2>Add a review:</h2>
		<%= form_with model: [ @product, @product.reviews.build ] do |form| %>
		  <p>
		    <%= form.label :content %><br>
		    <%= form.text_area :content %>
		  </p>
		  <p>
		    <%= form.submit %>
		  </p>
		<% end %>
  </div>
</div>










<style >
	body{
		background-color: red;
	}
	*{
		margin: 0px;
		padding: 0px;
	}
	.row{
		width: 400px;
		height: auto;
				
		background-color: white;
		margin-left: 30%;

	}
	h1{
		text-align: center;
		color: rgba(204, 43, 43, 0.8)

	}
	.ragister{
		color: blue;
		margin-left: 60px;
		
		font-size:22px;
	}
</style>